AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notify-to-line

  Sample SAM Template for notify-to-line

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Parameters:
  LineChannelSecret:
    Type: String
    Description: LINE Channel secret
  LineChannelToken:
    Type: String
    Description: LINE Channel access token

Resources:
  NotifyToLineFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: notify_to_line/
      Handler: app.lambda_handler
      Runtime: ruby3.2
      Architectures:
        - x86_64
      Environment:
        Variables:
          LINE_CHANNEL_SECRET: !Ref LineChannelSecret
          LINE_CHANNEL_TOKEN: !Ref LineChannelToken
      Events:
        IoT:
          Type: IoTRule
          Properties:
            Sql: SELECT device, time, clientid() AS client_id  FROM 'iot-button/notify-to-line'

Outputs:
  NotifyToLineFunction:
    Description: "Notify to LINE Lambda Function ARN"
    Value: !GetAtt NotifyToLineFunction.Arn
  NotifyToLineFunctionIamRole:
    Description: "Implicit IAM Role created for Notify to LINE function"
    Value: !GetAtt NotifyToLineFunctionRole.Arn
